import 'dart:io';
import 'package:finance_app/features/transactions/data/models/transaction_model.dart';
import 'package:finance_app/features/transactions/data/models/category_model.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class PdfExporter {
  static Future<File> generateTransactionsPdf({
    required List<TransactionModel> transactions,
    required List<CategoryModel> categories,
    required String title,
    required String currencySymbol,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (context) => pw.Column(
          children: [
            pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight:  pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.Divider(),
          ],
        ),
        build: (context) => [
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headers: ['Date', 'Category', 'Type', 'Amount', 'Note'],
            data: transactions.map((t) {
              final category = categories.cast<CategoryModel?>().firstWhere(
                (c) => c?.id == t.categoryId,
                orElse: () => null,
              );
              return [
                DateFormat('MMM d, yyyy').format(t.date),
                category?.name ?? 'Uncategorized',
                t.type.toUpperCase(),
                '$currencySymbol${t.amount.toStringAsFixed(2)}',
                t.note,
              ];
            }).toList(),
          ),
        ],
        footer: (context) => pw.Column(
          children: [
            pw.Divider(),
            pw.SizedBox(height: 10),
            pw.Text(
              'Generated by Hisab - ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/hisab_report_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
